--[[
Copyright (c) 2006-2010 LOVE Development Team

This software is provided 'as-is', without any express or implied
warranty.  In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required.
2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.
3. This notice may not be removed or altered from any source distribution.
--]]

do

	local vera_ttf_b64 = [[
[encoded data, 89133 characters]
]]

	love.graphics.newFont = function(font, size)
		if type(font) == "number" or not font then
			size = font
			font = love.filesystem.newFileData(vera_ttf_b64, "Vera.ttf", "base64")
		end
		return love.graphics.newFont1(font, size or 12)
	end

	love.graphics.setFont = function(font, size)
		if type(font) == "number" or not font then
			size = font
			font = love.filesystem.newFileData(vera_ttf_b64, "Vera.ttf", "base64")
		end
		return love.graphics.setFont1(font, size or 12)
	end

	love.graphics.print = function (...)
		if not love.graphics.getFont() then
			love.graphics.setFont(12)
		end
		love.graphics.print1(...)
		love.graphics.print = love.graphics.print1
	end

	love.graphics.printf = function (...)
		if not love.graphics.getFont() then
			love.graphics.setFont(12)
		end
		love.graphics.printf1(...)
		love.graphics.printf = love.graphics.printf1
	end

end
